#### Imports

In [20]:
import pandas as pd # type: ignore
from countryinfo import CountryInfo # type: ignore

#### Code

In [29]:
vinhos = pd.read_csv("ExpVinho.csv",encoding='utf-8',sep=";")
paises = pd.read_csv("files/countries.csv",encoding='utf-8',sep=",")

In [34]:
vinhos

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2018,2018.1,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1
0,1,Afeganistão,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,11,46,0,0
1,2,África do Sul,0,0,0,0,0,0,0,0,...,0,0,26,95,4,21,0,0,0,0
2,3,"Alemanha, República Democrática",0,0,0,0,4168,2630,12000,8250,...,10794,45382,3660,25467,6261,32605,2698,6741,7630,45367
3,4,Angola,0,0,0,0,0,0,0,0,...,477,709,345,1065,0,0,0,0,4068,4761
4,5,Anguilla,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Tuvalu,0,0,0,0,0,0,0,0,...,0,0,0,0,2,4,0,0,0,0
124,125,Uruguai,0,0,0,0,0,0,0,0,...,7711,29617,6180,18497,0,0,136774,149842,637117,997367
125,126,Vanuatu,0,0,0,0,0,0,0,0,...,0,0,0,0,18,31,0,0,0,0
126,127,Venezuela,0,0,3200,2000,1350,750,11700,6458,...,71,355,0,0,4086,9808,26415,35944,23220,32351
127,128,Vietnã,0,0,0,0,0,0,0,0,...,0,0,20,32,86,584,0,0,130,277

In [30]:
paises

,Nome,Nome-EN,Id,Continente,Sub-Regiao,Historico
0,Andorra,Andorra,AD,Europa,Europa meridional (Sul da Europa),O Principado de Andorra é um dos menores Estad...
1,Emirados Árabes Unidos,United Arab Emirates,AE,Ásia,Ásia ocidental (Oeste da Ásia),Os Emirados Árabes Unidos constituem um país l...
2,Afeganistão,Afghanistan,AF,Ásia,Ásia meridional (Sul da Ásia),A República Islâmica do Afeganistão é um país ...
3,Antígua e Barbuda,Antigua and Barbuda,AG,América,América Latina e Caribe,Antígua e Barbuda é um país constituído por du...
4,Albânia,Albania,AL,Europa,Europa meridional (Sul da Europa),A República da Albânia está localizada na pení...
...,...,...,...,...,...,...
188,Samoa,Samoa,WS,Oceania,Polinésia,Samoa é um país localizado no centro do Oceano...
189,Iêmen,Yemen,YE,Ásia,Ásia ocidental (Oeste da Ásia),O Iêmen é um país situado no canto sudoeste da...
190,África do Sul,South Africa,ZA,África,África subsaariana,A África do Sul é um país localizado no extrem...
191,Zâmbia,Zambia,ZM,África,África subsaariana,A Zâmbia é um país sem litoral na África. Está...
192,Zimbábue,Zimbabwe,ZW,África,África subsaariana,O Zimbábue é um país sem litoral da África mer...

In [35]:
pd.merge(vinhos,paises,left_on='País',right_on='Nome', how='left')

,Id_x,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2021,2021.1,2022,2022.1,Nome,Nome-EN,Id_y,Continente,Sub-Regiao,Historico
0,1,Afeganistão,0,0,0,0,0,0,0,0,...,11,46,0,0,Afeganistão,Afghanistan,AF,Ásia,Ásia meridional (Sul da Ásia),A República Islâmica do Afeganistão é um país ...
1,2,África do Sul,0,0,0,0,0,0,0,0,...,0,0,0,0,África do Sul,South Africa,ZA,África,África subsaariana,A África do Sul é um país localizado no extrem...
2,3,"Alemanha, República Democrática",0,0,0,0,4168,2630,12000,8250,...,2698,6741,7630,45367,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Angola,0,0,0,0,0,0,0,0,...,0,0,4068,4761,Angola,Angola,AO,África,África subsaariana,Angola é um pais localizado na costa ocidental...
4,5,Anguilla,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Tuvalu,0,0,0,0,0,0,0,0,...,0,0,0,0,Tuvalu,Tuvalu,TV,Oceania,Polinésia,Tuvalu é um país localizado no centro-oeste do...
124,125,Uruguai,0,0,0,0,0,0,0,0,...,136774,149842,637117,997367,Uruguai,Uruguay,UY,América,América Latina e Caribe,O Uruguai é um país localizado na costa sudest...
125,126,Vanuatu,0,0,0,0,0,0,0,0,...,0,0,0,0,Vanuatu,Vanuatu,VU,Oceania,Melanésia,Vanuatu é um país localizado no sudoeste do Oc...
126,127,Venezuela,0,0,3200,2000,1350,750,11700,6458,...,26415,35944,23220,32351,NaN,NaN,NaN,NaN,NaN,NaN
127,128,Vietnã,0,0,0,0,0,0,0,0,...,0,0,130,277,Vietnã,Viet Nam,VN,Ásia,Sudeste da Ásia,O Vietnã é um país que ocupa a porção leste do...